# Generated by Django 4.1 on 2022-08-14 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('help_image', models.ImageField(blank=True, default='', upload_to='')),
                ('helpset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexemes', to='api.helpset')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('helpset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='api.helpset')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('parse_data', models.CharField(blank=True, default='', max_length=200)),
                ('helpset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.helpset')),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.lexeme')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='lexeme',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.root'),
        ),
        migrations.AddConstraint(
            model_name='root',
            constraint=models.UniqueConstraint(fields=('text', 'helpset'), name='root_text_unique'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('word', 'lexeme'), name='word_lexeme_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='lexeme',
            constraint=models.UniqueConstraint(fields=('text', 'helpset'), name='lexeme_text_unqiue'),
        ),
    ]
