# Generated by Django 4.1 on 2022-08-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_word_lexemes_lexeme_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lexeme',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='root',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['text']},
        ),
        migrations.AlterField(
            model_name='helpset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='helpset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexemes', to='api.helpset'),
        ),
    ]
