# Generated by Django 4.1 on 2022-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lexeme_options_alter_root_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexeme',
            name='help_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
