# Generated by Django 4.1 on 2022-08-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lexeme_help_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='helpset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.helpset'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lexeme',
            constraint=models.UniqueConstraint(fields=('text', 'helpset'), name='lexeme_text_unqiue'),
        ),
        migrations.AddConstraint(
            model_name='root',
            constraint=models.UniqueConstraint(fields=('text', 'helpset'), name='root_text_unique'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('helpset', 'text'), name='word_text_unique'),
        ),
    ]
