# Generated by Django 4.1 on 2022-08-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_word_helpset_lexeme_lexeme_text_unqiue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='lexeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.lexeme'),
        ),
        migrations.AlterField(
            model_name='link',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.word'),
        ),
    ]
